version: '2.0'

services:
  squid:
    image: sameersbn/squid:3.3.8-23
    ports:
      - "3128:3128"
    volumes:
      - /home/ubuntu/software/services/starter/squid/data:/var/spool/squid3
      - /home/ubuntu/software/services/starter/squid/squid.conf:/etc/squid/squid.conf
    restart: always
