{
 "title": "market",
 "time": { "from": "2019-07-02T00:59:51.791Z", "to": "2019-07-02T07:29:49.068Z" },
 "panels": [
  { "title": "Panel Title", "type": "gauge", "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 } },
  {
   "title": "step_latency",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(step_latency_histogram_bucket[30m])) by (le))",
     "legendFormat": "99%"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(step_latency_histogram_bucket[30m])) by (le))",
     "legendFormat": "95%"
    },
    {
     "expr": "histogram_quantile(0.80, sum(rate(step_latency_histogram_bucket[30m])) by (le))",
     "legendFormat": "85%"
    },
    {
     "expr": "histogram_quantile(0.65, sum(rate(step_latency_histogram_bucket[30m])) by (le))",
     "legendFormat": "65%"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(step_latency_histogram_bucket[30m])) by (le))",
     "legendFormat": "50%"
    }
   ]
  },
  {
   "title": "get_today_all",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(get_today_all_histogram_bucket[30m])) by (le))",
     "legendFormat": "99%"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(get_today_all_histogram_bucket[30m])) by (le))",
     "legendFormat": "95%"
    },
    {
     "expr": "histogram_quantile(0.80, sum(rate(get_today_all_histogram_bucket[30m])) by (le))",
     "legendFormat": "85%"
    },
    {
     "expr": "histogram_quantile(0.65, sum(rate(get_today_all_histogram_bucket[30m])) by (le))",
     "legendFormat": "65%"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(get_today_all_histogram_bucket[30m])) by (le))",
     "legendFormat": "50%"
    }
   ]
  },
  {
   "title": "label_data",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(label_data_histogram_bucket[30m])) by (le))",
     "legendFormat": "99%"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(label_data_histogram_bucket[30m])) by (le))",
     "legendFormat": "95%"
    },
    {
     "expr": "histogram_quantile(0.80, sum(rate(label_data_histogram_bucket[30m])) by (le))",
     "legendFormat": "85%"
    },
    {
     "expr": "histogram_quantile(0.65, sum(rate(label_data_histogram_bucket[30m])) by (le))",
     "legendFormat": "65%"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(label_data_histogram_bucket[30m])) by (le))",
     "legendFormat": "50%"
    }
   ]
  },
  {
   "title": "send_kafka",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(send_kafka_histogram_bucket[30m])) by (le))",
     "legendFormat": "99%"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(send_kafka_histogram_bucket[30m])) by (le))",
     "legendFormat": "95%"
    },
    {
     "expr": "histogram_quantile(0.80, sum(rate(send_kafka_histogram_bucket[30m])) by (le))",
     "legendFormat": "85%"
    },
    {
     "expr": "histogram_quantile(0.65, sum(rate(send_kafka_histogram_bucket[30m])) by (le))",
     "legendFormat": "65%"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(send_kafka_histogram_bucket[30m])) by (le))",
     "legendFormat": "50%"
    }
   ]
  }
 ]
}