up:
	docker exec -it superset superset fab create-admin \
               --username liuwen \
               --firstname liu \
               --lastname wen \
               --email liuwen.w@qq.com \
               --password $(SUPERSET_PASSWD)

down:
	docker down superset


stop:
	docker stop superset 
