version: '3'

services:
  clickhouse:
    image: yandex/clickhouse-server:20.8
    container_name: clickhouse
    user: root
    restart: always
    ports:
      - "8123:9000"
    volumes:
      - ./etc:/etc/clickhouse-server
      - ${DATA_HOME}/clickhouse:/var/lib/clickhouse
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    privileged: true
