{
 "title": "market",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "最近开盘日期",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT max(start_date) from market.tasks;"
    }
   ]
  },
  {
   "title": "Basics",
   "type": "singlestat",
   "description": "股票基础信息",
   "gridPos": { "h": 2, "w": 2, "x": 3, "y": 0 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select (1.0-t2.undispatched/t1.total)*100 as finished from\n(select count(*) as total from market.tasks WHERE \nstart_date=(SELECT max(start_date) from market.tasks) \nand task_type='daily_basic') t1, \n(select count(*) as undispatched from market.tasks WHERE \nstart_date=(SELECT max(start_date) from market.tasks) \nand task_type='daily_basic' and `status`='undispatched') t2;"
    }
   ]
  },
  {
   "title": "Indexs",
   "type": "singlestat",
   "description": "每日股票指数任务",
   "gridPos": { "h": 2, "w": 2, "x": 5, "y": 0 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select (1.0-t2.undispatched/t1.total)*100 as finished from\n(select count(*) as total from market.tasks WHERE \nstart_date=(SELECT max(start_date) from market.tasks) \nand task_type='index_daily') t1, \n(select count(*) as undispatched from market.tasks WHERE \nstart_date=(SELECT max(start_date) from market.tasks) \nand task_type='index_daily' and `status`='undispatched') t2;"
    }
   ]
  },
  {
   "title": "Daily",
   "type": "singlestat",
   "description": "个股每日数据下载任务",
   "gridPos": { "h": 2, "w": 2, "x": 7, "y": 0 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select (1.0-t2.undispatched/t1.total)*100 as finished from\n(select count(*) as total from market.tasks WHERE \nstart_date=(SELECT max(start_date) from market.tasks) \nand task_type='daily') t1, \n(select count(*) as undispatched from market.tasks WHERE \nstart_date=(SELECT max(start_date) from market.tasks) \nand task_type='daily' and `status`='undispatched') t2;"
    }
   ]
  },
  {
   "title": "概念明细数",
   "type": "singlestat",
   "description": "个股每日数据下载任务",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select count(*) from market.code_tags where src='ths';"
    }
   ]
  },
  {
   "title": "历史作业完成情况",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(STR_TO_DATE(start_date, '%Y%m%d')) as time_sec,\n  count(*) as value,\n  `status` as metric\nFROM market.tasks\nwhere start_date>'20190501' and task_type='daily'\nGROUP BY start_date, `status`\nORDER BY start_date ASC\n"
    }
   ]
  },
  {
   "title": "单次实时数据处理",
   "type": "graph",
   "description": "realtime step latency, local_realtime_worker.py:  run_step",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "none", "label": "时间(s)" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(step_latency_histogram_bucket[30m])) by (le))",
     "legendFormat": "99%"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(step_latency_histogram_bucket[30m])) by (le))",
     "legendFormat": "95%"
    },
    {
     "expr": "histogram_quantile(0.80, sum(rate(step_latency_histogram_bucket[30m])) by (le))",
     "legendFormat": "85%"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(step_latency_histogram_bucket[30m])) by (le))",
     "legendFormat": "50%"
    }
   ]
  },
  {
   "title": "数据打标",
   "type": "graph",
   "description": "local_realtime_worker.py: label_data",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "none", "label": "时间(s)" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(label_data_histogram_bucket[30m])) by (le))",
     "legendFormat": "99%"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(label_data_histogram_bucket[30m])) by (le))",
     "legendFormat": "95%"
    },
    {
     "expr": "histogram_quantile(0.80, sum(rate(label_data_histogram_bucket[30m])) by (le))",
     "legendFormat": "85%"
    },
    {
     "expr": "histogram_quantile(0.65, sum(rate(label_data_histogram_bucket[30m])) by (le))",
     "legendFormat": "65%"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(label_data_histogram_bucket[30m])) by (le))",
     "legendFormat": "50%"
    }
   ]
  },
  {
   "title": "提交到kafka",
   "type": "graph",
   "description": "local_realtime_worker.py: send_kafka",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "none", "label": "时间(s)" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(send_kafka_histogram_bucket[30m])) by (le))",
     "legendFormat": "99%"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(send_kafka_histogram_bucket[30m])) by (le))",
     "legendFormat": "95%"
    },
    {
     "expr": "histogram_quantile(0.80, sum(rate(send_kafka_histogram_bucket[30m])) by (le))",
     "legendFormat": "85%"
    },
    {
     "expr": "histogram_quantile(0.65, sum(rate(send_kafka_histogram_bucket[30m])) by (le))",
     "legendFormat": "65%"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(send_kafka_histogram_bucket[30m])) by (le))",
     "legendFormat": "50%"
    }
   ]
  },
  {
   "title": "每天实时数据获取",
   "type": "graph",
   "description": "tushare.get_today_all()",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "none", "label": "时间(s)" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(get_today_all_histogram_bucket[30m])) by (le))",
     "legendFormat": "99%"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(get_today_all_histogram_bucket[30m])) by (le))",
     "legendFormat": "95%"
    },
    {
     "expr": "histogram_quantile(0.80, sum(rate(get_today_all_histogram_bucket[30m])) by (le))",
     "legendFormat": "85%"
    },
    {
     "expr": "histogram_quantile(0.65, sum(rate(get_today_all_histogram_bucket[30m])) by (le))",
     "legendFormat": "65%"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(get_today_all_histogram_bucket[30m])) by (le))",
     "legendFormat": "50%"
    }
   ]
  }
 ]
}