{
 "title": "Nvidia GPU",
 "description": "GPU dashboard for nvidia metrics ",
 "tags": [
  "gpu",
  "cluster",
  "hardware",
  "infrastructure"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 } },
  {
   "title": "GPU Utilization",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "dcgm_gpu_utilization" }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 7, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "dcgm_fb_used / (81.92)" }
   ]
  },
  {
   "title": "GPU Utilization / Card",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 10, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "dcgm_gpu_utilization", "legendFormat": "gpu {{ gpu }}" }
   ]
  },
  {
   "title": "Memory Utilization ",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 0 },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    { "expr": "dcgm_fb_used", "legendFormat": "gpu {{ gpu }}" }
   ]
  },
  {
   "title": "GPU Temperature",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    { "expr": "dcgm_gpu_temp", "legendFormat": "gpu: {{ gpu }}" }
   ]
  },
  {
   "title": "Power Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 7, "y": 6 },
   "yaxes": [
    { "format": "mwatt" }
   ],
   "targets": [
    { "expr": "dcgm_power_usage", "legendFormat": "gpu: {{ gpu }}" }
   ]
  },
  {
   "title": "GPU PCIe RX接收的字节总数",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 15, "y": 6 },
   "yaxes": [
    { "format": "kbytes" }
   ],
   "targets": [
    { "expr": "dcgm_pcie_tx_throughput", "legendFormat": "gpu {{ gpu }}" }
   ]
  },
  {
   "title": "GPU PCIe TX传输的字节总数 ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 15, "y": 12 },
   "yaxes": [
    { "format": "kbytes" }
   ],
   "targets": [
    { "expr": "dcgm_pcie_tx_throughput", "legendFormat": "gpu {{ gpu }}" }
   ]
  },
  {
   "title": "Fan Speed",
   "type": "graph",
   "gridPos": { "h": 6, "w": 15, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "dcgm_f", "legendFormat": "{{kubernetes_pod_node_name}}" }
   ]
  }
 ]
}