{
 "title": "Task Server",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "day",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select (1.0-t2.undispatched/t1.total)*100 as finished from\n(select count(*) as total from tasks WHERE \nstart_date=(SELECT max(start_date) from tasks) \nand task_type='day') t1, \n(select count(*) as undispatched from tasks WHERE \nstart_date=(SELECT max(start_date) from tasks) \nand task_type='day' and `status`='undispatched') t2;\n\n"
    }
   ]
  },
  {
   "title": "Tasks",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 3, "y": 0 },
   "targets": [
    {
     "rawSql": "select task_type, `status`, count(*) as number from felt.tasks group by task_type, `status`;"
    }
   ]
  },
  {
   "title": "Tasks",
   "type": "table",
   "gridPos": { "h": 7, "w": 9, "x": 11, "y": 0 },
   "targets": [
    {
     "rawSql": "select task_type, `status`, count(*) as number from felt_pro.tasks group by task_type, `status`;"
    }
   ]
  },
  {
   "title": "index_daily",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 20, "y": 0 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select 1.0-t2.undispatched/t1.total as finished from\n(select count(*) as total from felt_pro.tasks WHERE \nstart_date=(SELECT max(start_date) from felt_pro.tasks) \nand task_type='index_daily') t1, \n(select count(*) as undispatched from felt_pro.tasks WHERE \nstart_date=(SELECT max(start_date) from felt_pro.tasks) \nand task_type='index_daily' and `status`='undispatched') t2;\n\n"
    }
   ]
  },
  {
   "title": "daily",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 20, "y": 3 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select (1.0-t2.undispatched/t1.total)*100 as finished from\n(select count(*) as total from felt_pro.tasks WHERE \nstart_date=(SELECT max(start_date) from felt_pro.tasks) \nand task_type='daily') t1, \n(select count(*) as undispatched from felt_pro.tasks WHERE \nstart_date=(SELECT max(start_date) from felt_pro.tasks) \nand task_type='daily' and `status`='undispatched') t2;\n\n"
    }
   ]
  },
  {
   "title": "get_h_data",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select 1.0-t2.undispatched/t1.total as finished from\n(select count(*) as total from tasks WHERE \nstart_date=(SELECT max(start_date) from tasks) \nand task_type='get_h_data') t1, \n(select count(*) as undispatched from tasks WHERE \nstart_date=(SELECT max(start_date) from tasks) \nand task_type='get_h_data' and `status`='undispatched') t2;\n\n"
    }
   ]
  },
  {
   "title": "Task index_daily",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "go_memstats_gc_cpu_fraction",
     "legendFormat": "{{ instance }}",
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(STR_TO_DATE(start_date, '%Y%m%d')) as time_sec,\n  count(*) as value,\n  `status` as metric\nFROM felt_pro.tasks\nwhere start_date>'20110801' and task_type='index_daily'\nGROUP BY start_date, `status`\nORDER BY start_date ASC\n"
    }
   ]
  },
  {
   "title": "Tasks daily",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 11, "y": 7 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "go_memstats_gc_cpu_fraction",
     "legendFormat": "{{ instance }}",
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(STR_TO_DATE(start_date, '%Y%m%d')) as time_sec,\n  count(*) as value,\n  `status` as metric\nFROM felt_pro.tasks\nwhere start_date>'20110801' and task_type='daily'\nGROUP BY start_date, `status`\nORDER BY start_date ASC\n"
    }
   ]
  },
  {
   "title": "Old Task get_h_data",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "go_memstats_gc_cpu_fraction",
     "legendFormat": "{{ instance }}",
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(STR_TO_DATE(start_date, '%Y-%m-%d')) as time_sec,\n  count(*) as value,\n  `status` as metric\nFROM felt.tasks\nwhere start_date>'2011-08-01' and task_type='get_h_data'\nGROUP BY start_date, `status`\nORDER BY start_date ASC\n"
    }
   ]
  },
  {
   "title": "Tasks daily",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 11, "y": 14 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "go_memstats_gc_cpu_fraction",
     "legendFormat": "{{ instance }}",
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(STR_TO_DATE(start_date, '%Y-%m-%d')) as time_sec,\n  count(*) as value,\n  `status` as metric\nFROM felt.tasks\nwhere start_date>'2011-08-01' and task_type='day'\nGROUP BY start_date, `status`\nORDER BY start_date ASC\n"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "process_resident_memory_bytes", "legendFormat": "{{ instance }}" }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 11, "y": 21 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    { "expr": "go_memstats_gc_cpu_fraction", "legendFormat": "{{ instance }}" }
   ]
  }
 ]
}