version: "3"

services:
  db:
    image: postgres:11.1
    container_name: postgresql
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - ${DATA_HOME}/postgresql:/var/lib/postgresql/data
