version: '2.0'

services:
  dispatcher:
    image: aiminders/libary:dispatcher.latest
    ports:
      - '9334:9334'
    volumes:
      - .:/root/dispatcher
    command:
      sh /root/dispatcher/run-dispatcher.sh
