version: "3.0"

services:
  redis:
    image: redis:6.0-alpine
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWD}
    ports:
      - 6379:6379
    volumes:
      - ${DATA_HOME}/redis:/data
