version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'mariadb_data:/bitnami'
  phabricator:
    image: 'bitnami/phabricator:latest'
    labels:
      kompose.service.type: nodeport
    ports:
      - '80:80'
      - '443:443'
    environment:
      - PHABRICATOR_HOST=${PHABRICATOR_HOST}
      - PHABRICATOR_USERNAME=${USER_NAME}
      - PHABRICATOR_PASSWORD=${PASSWD}
      - PHABRICATOR_EMAIL=${EMAIL}
    volumes:
      - './phabricator_data:/bitnami'
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
  phabricator_data:
    driver: local
