version: '2'
services:
  elasticsearch:
    image: 'bitnami/elasticsearch:7'
    volumes:
      - '/home/ubuntu/data/elasticsearch:/bitnami'
  kibana:
    image: 'bitnami/kibana:7'
    ports:
      - '5601:5601'
    volumes:
      - '/home/ubuntu/data/kibana:/bitnami'
    depends_on:
      - elasticsearch
volumes:
  elasticsearch_data:
    driver: local
  kibana_data:
    driver: local
