
# https://hub.docker.com/r/bitnami/kibana/tags
version: '2'
services:
  elasticsearch:
    image: 'bitnami/elasticsearch:latest'
    volumes:
      - '/home/ubuntu/data/elasticsearch:/bitnami'
  kibana:
    image: 'bitnami/kibana:latest'
    ports:
      - '5601:5601'
    volumes:
      - '/home/ubuntu/data/kibana:/bitnami'
    depends_on:
      - elasticsearch
volumes:
  elasticsearch_data:
    driver: local
  kibana_data:
    driver: local
