# https://github.com/deviantony/docker-elk/blob/master/docker-compose.yml
version: '3.2'

services:
  elasticsearch:
    image: registry.cn-hangzhou.aliyuncs.com/tradingai/elk:elasticsearch.latest
    volumes:
        - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
        - /tmp/data/elasticsearch:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: changeme
      # Use single node discovery in order to disable production mode and avoid bootstrap checks
      # see https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
      discovery.type: single-node
    networks:
      - elk

  logstash:
    image: registry.cn-hangzhou.aliyuncs.com/tradingai/elk:logstash.latest
    volumes:
      - ./logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    ports:
      - "5000:5000/tcp"
      - "5000:5000/udp"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    image: kibana:7.6.2
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

  filebeat:
    image: registry.cn-hangzhou.aliyuncs.com/tradingai/elk:filebeat.latest
    user: root
    name: filebeat
    command: filebeat -e -strict.perms=false
    volumes:
      - "./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro"
      - "/var/lib/docker/containers:/var/log/docker:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

networks:
  elk:
    driver: bridge
