filebeat.inputs:
    - type: log
      enabled: true
      paths:
          - /var/log/docker/*/*.log

json.keys_under_root: true

json.add_error_key: true

json.overwrite_keys: true

setup.kibana:
  host: http://192.168.1.107:5601
  username: elastic
  password: changeme

output.elasticsearch:
  hosts: ["http://192.168.1.107:9200"]
  username: elastic
  password: changeme

setup.template.name: "filebeattest"

setup.template.pattern: "filebeattest-*"
