filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true

processors:
- add_cloud_metadata: ~

setup.kibana:
  host: http://192.168.1.107:5601
  username: elastic
  password: changeme

output.elasticsearch:
  hosts: ["http://192.168.1.107:9200"]
  username: elastic
  password: changeme

# setup.template.name: "filebeattest"
#
# setup.template.pattern: "filebeattest-*"
